workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.22.0
      xcode: 15.4
    scripts:
      - name: Install unrar
        script: brew install unrar
      - name: Unzip project
        script: |
          unrar x jizhang.rar .
          ls -la
      - name: Flutter dependencies
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/Runner.ipa
