workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.22.0
      xcode: 15.4
    scripts:
      - name: 1. 安装解压工具并解压项目
        script: |
          brew install unrar
          unrar x jizhang.rar .
          ls -la
          # 找到 pubspec.yaml 所在目录
          export PROJECT_DIR=$(find . -name pubspec.yaml -type f -exec dirname {} \; | head -n 1)
          echo "项目根目录: $PROJECT_DIR"
      - name: 2. 进入项目目录并执行打包
        script: |
          cd $PROJECT_DIR
          pwd
          flutter pub get
          flutter build ipa --release
    artifacts:
      - $PROJECT_DIR/build/ios/ipa/*.ipa
